using JetBrains.Annotations;

namespace SchemaMigrations.Abstractions;

/// <summary>
/// Base class for all the migrations generated by Migration tool
/// </summary>
[PublicAPI]
public abstract class Migration
{
    /// <summary>
    /// List of newly generated guid for all the schemas
    /// </summary>
    public abstract Dictionary<string, Guid> GuidDictionary { get; }

    /// <summary>
    /// Generator tool overrides this method to affect all the SchemaContext and its SchemaSets changes
    /// </summary>
    public abstract void Up(MigrationBuilder migrationBuilder);
}