name: Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '!main'

jobs:
  windows:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish Nuget
        run: ./.nuke/build.cmd NuGetPush --NugetApiKey ${{ secrets.NUGET_TOKEN }}
      